DROP TABLE IF EXISTS prices;

CREATE TABLE prices (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    price NUMERIC NOT NULL,
    coin TEXT NOT NULL
);
